### ISSUE TITLE
Please add Staked

### ISSUE THREAD

**Issue by fzkvn** [AkifhanIlgaz/tek-zeki-sensin#3]
Sometimes the Mande webs didn't record even we already stake, its appear nothing to the receiver and the people who give but we already staked. if possible add column of staked too ill appreciate that. thank you.

**Comment by AkifhanIlgaz** [comment]
I get the data from the same API as the Mande website. So if it doesn't show on the Mande website, my website doesn't show also

**Comment by AkifhanIlgaz** [comment]
It's probably network or RPC error
